context("fast_imputation")

set.seed(42)
good_df <- data.frame(
  X1  = letters,
  X2  = 1:26,
  X3  = rnorm(26),
  X4  = rexp(26),
  X5  = runif(26),
  X6  = sample(c(TRUE, FALSE), 26, replace = TRUE),
  X7  = 3 - rexp(26),
  X8  = rnorm(26),
  X9  = rnorm(26),
  X10 = rnorm(26),
  X11 = rnorm(26)
)
good_constraints <- list(
  X7 = list(upper = 3),
  X4 = list(lower = 0),
  X5 = list(lower = 0, upper = 1)
)
good_ignore     <- c("X2", "X1")
good_categorical <- c("X6")

good_patterns <- train_fast_imputation(
  good_df,
  constraints = good_constraints,
  ignore_cols = tidyselect::all_of(good_ignore),
  categorical = tidyselect::all_of(good_categorical)
)

good_test_set <- data.frame(
  X1  = c("XX", "DD"),
  X2  = 5:6,
  X3  = c(NA, 1),
  X4  = 1:2,
  X5  = c(.25, .75),
  X6  = c(TRUE, NA),
  X7  = 1:2,
  X8  = rnorm(2),
  X9  = rnorm(2),
  X10 = rnorm(2),
  X11 = rnorm(2)
)

good_imputed_set <- fast_imputation(good_test_set, patterns = good_patterns, verbose = FALSE)

bad_df    <- data.frame(X3 = rnorm(5), X6 = sample(c(TRUE, FALSE), 5, replace = TRUE))
bad_array <- matrix(1:9, nrow = 3)

test_that("fast_imputation catches bad input", {
  expect_error(
    fast_imputation(good_test_set, verbose = FALSE),
    "A 'patterns' object generated by 'train_fast_imputation' must be specified."
  )
  expect_error(
    fast_imputation(good_test_set, patterns = 5, verbose = FALSE),
    "'patterns' must be of class 'fast_imputation_patterns'."
  )
  expect_error(
    fast_imputation(bad_array, patterns = good_patterns, verbose = FALSE),
    "'x' must be a data frame."
  )
  expect_error(
    fast_imputation(bad_df, patterns = good_patterns, verbose = FALSE),
    "The names of the variables you are imputing don't match"
  )
})

test_that("fast_imputation returns correct types", {
  expect_true(is.data.frame(good_imputed_set))
})

test_that("fast_imputation is pipe-friendly", {
  result <- good_test_set |> fast_imputation(good_patterns, verbose = FALSE)
  expect_true(is.data.frame(result))
  expect_equal(ncol(result), ncol(good_test_set))
})

test_that("fast_imputation returns tibble when input is tibble", {
  tbl_test <- tibble::as_tibble(good_test_set)
  result   <- fast_imputation(tbl_test, patterns = good_patterns, verbose = FALSE)
  expect_s3_class(result, "tbl_df")
})

test_that("fast_imputation fills in missing values", {
  expect_false(is.na(good_imputed_set$X3[1]))
  expect_false(is.na(good_imputed_set$X6[2]))
})
