#' Use the pattern learned from the training data to impute (fill in good guesses for) missing values.
#'
#' Like Amelia, FastImputation assumes that the columns of the data are
#' multivariate normal or can be transformed into approximately
#' multivariate normal.
#' 
#' @param x Vector, matrix, dataframe, or object that can be coerced into a dataframe, possibly with some missing (\code{NA}) values.
#' @param patterns An object of class 'FastImputationPatterns' generated by \code{TrainFastImputation}.
#' @param verbose If TRUE then the progress in imputing the data will be shown.
#' @return x, but with missing values filled in (imputed)
#' @export
#' @seealso \code{\link{TrainFastImputation}}
#' @references
#' \url{http://gking.harvard.edu/amelia/}
#' @author Stephen R. Haptonstahl \email{srh@@haptonstahl.org}
#' @examples
#' data(FI_train)   # provides FItrain dataset
#' patterns <- TrainFastImputation(
#'   FI_train,
#'   constraints=list(list(2, list(lower=0)),           # continuous var with lower bound
#'                    list(5, list(upper=0)),           # continuous var with only upper bound
#'                    list(6, list(lower=0, upper=1))   # bounded to a finite interval
#'                    ),
#'   idvars=1,  # user ids; also used for any variable not to be imputed
#'   categorical=9)
#' 
#' data(FI_test)
#' FI_test          # note there is missing data
#' \dontrun{imputed.data <- FastImputation(FI_test, patterns)}
#' \dontrun{imputed.data    # good guesses for missing values are filled in}
#'
#' data(FI_true)
#' \dontrun{imputation.rmse <- sqrt(sum( (imputed.data - FI_true)^2 )/sum(is.na(FI_test)))}
#' \dontrun{imputation.rmse}
#' 
#' \dontrun{library("caret")}
#' \dontrun{confusionMatrix(data=imputed.data$V9, reference=FI_true$V9)}
#' 
FastImputation <-
function(
  x,
  patterns,
  verbose=TRUE
) {
  if( missing(patterns) ) {
    stop("A 'patterns' object must be specified.")
  } else {
    if( class(patterns) != "FastImputationPatterns" ) stop("'patterns' must be of class 'FastImputationPatterns'. This is generated by appropriate use of the 'TrainFastImputation' function.")
  }
  if( is.vector(x) && is.numeric(x) ) x <- as.data.frame(t(x))
  if( !is.data.frame(x) && is.matrix(x) ) x <- as.data.frame(x)
  if( !is.data.frame(x) ) stop("'x' must be a vector, matrix, or dataframe.")
  
  n.cols <- length(patterns$FI.means)
  n.rows <- nrow(x)
  
  if(verbose) pb <- utils::txtProgressBar(style=3)
  
  for(i.row in 1:n.rows) {
    # Transform present data if constrained to an interval
    constrained.row <- x[i.row,]
    if( sum(!is.na(constrained.row)) != 0 ) {
      for(i in patterns$FI.cols.bound.to.intervals) {
        if( !is.na(constrained.row[i]) ) {
          constrained.row[i] <- NormalizeBoundedVariable(
            x=constrained.row[i],
            constraints=patterns$FI.constraints[[i]])
        } 
      }
    }
  
    # Use formula for mean here: http://en.wikipedia.org/wiki/Multivariate_normal_distribution#Conditional_distributions
    cols.to.impute <- which(is.na(constrained.row))    # indices of "1" in Wikipedia formula for mean of conditional multivariate normal distribution
    if( length(cols.to.impute) > 0 ) {
      if( length(cols.to.impute) == length(constrained.row) ) {
        replacement.values <- patterns$FI.means
      } else {
        known.cols <- setdiff(1:n.cols, cols.to.impute)  # incides of "2" in Wikipedia formula for mean of conditional multivariate normal distribution
        
        replacement.values <- t(t(patterns$FI.means[cols.to.impute])) + 
          patterns$FI.covariance[cols.to.impute,known.cols, drop=FALSE] %*% 
          solve(a=patterns$FI.covariance[known.cols,known.cols], 
                b=t(constrained.row[known.cols]) - t(t(patterns$FI.means[known.cols])))
      }
      # Store replacement values (note that constraints are not yet applied)
      x[i.row,cols.to.impute] <- replacement.values ### PERHAPS ADD as.vector to RHS
    
      # Constrain interval cols
      imputed.cols.constrained.to.intervals <- intersect(patterns$FI.cols.bound.to.intervals, cols.to.impute)
      for(i in imputed.cols.constrained.to.intervals) {
        x[i.row, i] <- BoundNormalizedVariable(x[i.row, i], constraints=patterns$FI.constraints[[i]])
      }
    
      # Constrain set cols
      imputed.cols.constrained.to.sets <- intersect(patterns$FI.cols.bound.to.sets, cols.to.impute)
      for(i in imputed.cols.constrained.to.sets) {
        x[i.row, i] <- LimitToSet(x[i.row, i], set=patterns$FI.constraints[[i]]$set)
      }
    }
    if(verbose) utils::setTxtProgressBar(pb, i.row/n.rows)
  }
  if(verbose) { 
    close(pb)
    cat("\n")
  }
  return(x)
}
