#' Use patterns learned from training data to impute missing values
#'
#' Like Amelia, FastImputation assumes that the columns of the data are
#' multivariate normal or can be transformed into approximately
#' multivariate normal.
#'
#' @param x A data frame or tibble, possibly with some missing (\code{NA})
#'   values. Must have the same columns in the same order as the training data
#'   passed to \code{\link{train_fast_imputation}}.
#' @param patterns An object of class \code{fast_imputation_patterns} generated
#'   by \code{\link{train_fast_imputation}}.
#' @param verbose If \code{TRUE} a progress bar is shown. Default \code{FALSE}.
#' @return \code{x} with missing values filled in. Returns a tibble if
#'   \code{x} is a tibble, otherwise a data frame.
#' @export
#' @seealso \code{\link{train_fast_imputation}}
#' @references \url{https://gking.harvard.edu/amelia}
#' @author Stephen R. Haptonstahl \email{srh@@haptonstahl.org}
#' @examples
#' data(FI_train)
#' patterns <- train_fast_imputation(
#'   FI_train,
#'   constraints = list(
#'     bounded_below_2           = list(lower = 0),
#'     bounded_above_and_below_6 = list(lower = 0, upper = 1)
#'   ),
#'   ignore_cols = user_id_1,
#'   categorical = categorical_9
#' )
#'
#' data(FI_test)
#' imputed_data <- fast_imputation(FI_test, patterns)
#'
fast_imputation <-
  function(
    x,
    patterns,
    verbose = FALSE
  ) {
    if (missing(patterns)) {
      rlang::abort(
        "A 'patterns' object generated by 'train_fast_imputation' must be specified."
      )
    }
    if (!methods::is(patterns, "fast_imputation_patterns")) {
      rlang::abort(
        paste0(
          "'patterns' must be of class 'fast_imputation_patterns'. ",
          "This is generated by appropriate use of the 'train_fast_imputation' function."
        )
      )
    }
    if (!inherits(x, "data.frame")) rlang::abort("'x' must be a data frame.")
    if (!identical(names(x), patterns$var_names)) {
      rlang::abort(
        paste0(
          "The names of the variables you are imputing don't match those of the ",
          "training data. Check to make sure the data is in the same format with ",
          "the same columns in the same order."
        )
      )
    }

    was_tibble <- tibble::is_tibble(x)
    names_imputing_set <- names(x)

    # Remove cols to ignore
    if (length(patterns$cols_to_ignore) > 0) {
      y <- x[, -patterns$cols_to_ignore, drop = FALSE]
    } else {
      y <- x
    }

    # Transform constrained columns
    for (i_col in patterns$cols_bound) {
      y[, i_col] <- normalize_bounded_variable(
        y[, i_col],
        patterns$constraints[[i_col]]
      )
    }

    # Set aside categorical variables and one-hot encode them
    if (length(patterns$cols_categorical) > 0) {
      y_categorical <- y[, patterns$cols_categorical, drop = FALSE]
      z <- y[, -patterns$cols_categorical, drop = FALSE]
      total_not_categorical <- ncol(z)

      total_one_hot_dummies <- sum(vapply(patterns$categories, length, integer(1)))
      z <- data.frame(
        z,
        matrix(NA_real_, nrow = nrow(z), ncol = total_one_hot_dummies)
      )
      current_col_to_fill <- 1
      while (current_col_to_fill <= total_one_hot_dummies) {
        for (i in seq_along(patterns$categories)) {
          for (j in seq_along(patterns$categories[[i]])) {
            z[, total_not_categorical + current_col_to_fill] <- ifelse(
              y_categorical[, i] == patterns$categories[[i]][j],
              1,
              -1
            )
            current_col_to_fill <- current_col_to_fill + 1
          }
        }
      }
    } else {
      z <- y
    }

    if (verbose) pb <- utils::txtProgressBar(style = 3)
    n_rows <- nrow(z)
    n_cols <- ncol(z)

    for (i_row in 1:n_rows) {
      constrained_row <- z[i_row, ]
      if (sum(is.na(constrained_row)) != 0) {
        cols_to_impute <- which(is.na(constrained_row))
        if (length(cols_to_impute) == length(constrained_row)) {
          replacement_values <- patterns$means
        } else {
          known_cols <- setdiff(1:n_cols, cols_to_impute)
          replacement_values <- t(t(patterns$means[cols_to_impute])) +
            patterns$covariance[cols_to_impute, known_cols, drop = FALSE] %*%
              solve(
                a = patterns$covariance[known_cols, known_cols],
                b = t(constrained_row[known_cols]) -
                  t(t(patterns$means[known_cols]))
              )
        }
        z[i_row, cols_to_impute] <- replacement_values
      }
      if (verbose) utils::setTxtProgressBar(pb, i_row / n_rows)
    }
    if (verbose) {
      close(pb)
      cat("\n")
    }

    # Recover categorical variables
    if (length(patterns$cols_categorical) > 0) {
      for (i_col in seq_len(ncol(y_categorical))) {
        n_cols_this_var <- length(patterns$categories[[i_col]])
        cat_indices <- apply(
          z[,
            (total_not_categorical + 1):(total_not_categorical + n_cols_this_var),
            drop = FALSE
          ],
          1,
          which.max
        )
        y_categorical[, i_col] <- patterns$categories[[i_col]][cat_indices]
        total_not_categorical <- total_not_categorical + n_cols_this_var
      }
      # Reset total_not_categorical to rebuild y from z
      total_not_categorical <- ncol(z) - sum(vapply(patterns$categories, length, integer(1)))
      y <- z[, 1:total_not_categorical, drop = FALSE]
      for (i in seq_len(ncol(y_categorical))) {
        y_col <- patterns$cols_categorical[i]
        y <- as.data.frame(append(
          y,
          list(var = y_categorical[, i, drop = FALSE]),
          y_col - 1
        ))
      }
    } else {
      y <- z
    }

    # Coerce categorical variables to factors with correct levels
    for (i in seq_along(patterns$cols_categorical)) {
      y[[patterns$cols_categorical[i]]] <- factor(
        y[[patterns$cols_categorical[i]]],
        levels = patterns$categories[[i]]
      )
    }

    # Bound normalized variables
    for (i_col in patterns$cols_bound) {
      y[, i_col] <- bound_normalized_variable(
        y[, i_col],
        patterns$constraints[[i_col]]
      )
    }

    # Add ignored columns back
    if (length(patterns$cols_to_ignore) > 0) {
      for (i_col in patterns$cols_to_ignore) {
        y <- as.data.frame(append(y, list(var = x[, i_col]), i_col - 1))
      }
    }

    names(y) <- names_imputing_set

    if (was_tibble) y <- tibble::as_tibble(y)
    return(y)
  }
